// Creates fpml-<version>-<view> projects from FpML "Schema and Examples" downloads, adds them to FpmlToolKit.slnx,
// and copies a few of the official examples into the test project.
//
//   dotnet run scripts/add-schema-version.cs -- <folder> [<folder> ...]
//   dotnet run scripts/add-schema-version.cs              (only regenerate the per-version package projects)
//
// Each folder is searched recursively for fpml-main-*.xsd; every match is one view (confirmation, reporting, ...).
// The version comes from the main schema's file name (fpml-main-5-13.xsd -> 5-13) and the view from its target
// namespace (http://www.fpml.org/FpML-5/confirmation -> confirmation).
//
// - The schema must compile (System.Xml.Schema) or the view is skipped; LinqToXsd fails silently on such schemas.
// - The XSDs next to the main schema are copied into the new project's xsd/ folder.
// - ExamplesPerView schema-valid example documents, spread evenly across the view's examples, are copied to
//   tests/FpmlToolKit.Tests/Examples/<project>/, keeping their relative paths.
// - packages/FpmlToolKit.Fpml<version>/ is (re)generated for every FpML version in the repository: one NuGet package
//   per version, containing all of that version's view projects (see build/VersionPackage.targets).
// Existing projects and existing example folders are left untouched, so the script is safe to re-run.

#nullable enable

using System.Diagnostics;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;

const int ExamplesPerView = 5;
const long MaxExampleBytes = 100_000;

var repoRoot = FindRepoRoot();
var sources = args.Where(a => !a.StartsWith("--")).ToList();

foreach (var missing in sources.Where(s => !Directory.Exists(s)))
{
    Console.Error.WriteLine($"folder not found: {missing}");
    return 1;
}

var mainSchemas = sources
    .SelectMany(s => Directory.GetFiles(s, "fpml-main-*.xsd", SearchOption.AllDirectories))
    .Order()
    .ToList();
if (sources.Count > 0 && mainSchemas.Count == 0)
{
    Console.Error.WriteLine("no fpml-main-*.xsd found");
    return 1;
}

var failed = 0;
foreach (var mainSchema in mainSchemas)
{
    try
    {
        Add(mainSchema);
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"{mainSchema}: {ex.Message}");
        failed++;
    }
}
WriteVersionPackages();
return failed == 0 ? 0 : 1;

void WriteVersionPackages()
{
    var views = Directory.GetDirectories(repoRoot, "fpml-*")
        .Select(Path.GetFileName)
        .OfType<string>()
        .Where(n => File.Exists(Path.Combine(repoRoot, n, n + ".csproj")))
        .Select(n => (Name: n, Match: Regex.Match(n, @"^fpml-(\d+)-(\d+)(?:-([a-z]+))?$")))
        .Where(x => x.Match.Success)
        .GroupBy(x => (Major: int.Parse(x.Match.Groups[1].Value), Minor: int.Parse(x.Match.Groups[2].Value)))
        .OrderBy(g => g.Key);

    foreach (var version in views)
    {
        var (major, minor) = version.Key;
        var packageId = $"FpmlToolKit.Fpml{major}{minor}";
        var projects = version.Select(x => x.Name).Order(StringComparer.Ordinal).ToList();
        var viewNames = version.Select(x => x.Match.Groups[3].Value).Where(v => v.Length > 0).Order(StringComparer.Ordinal).ToList();
        var description = viewNames.Count == 0
            ? $"Strongly typed LINQ to XSD classes for FpML {major}.{minor}."
            : $"Strongly typed LINQ to XSD classes for FpML {major}.{minor}, one assembly per view: {string.Join(", ", viewNames)}.";

        var references = string.Join(Environment.NewLine, projects.Select(p => $"""    <ProjectReference Include="..\..\{p}\{p}.csproj" />"""));
        var schemas = string.Join(Environment.NewLine, projects.Select(p => $"""    <None Include="..\..\{p}\xsd\**" Pack="true" PackagePath="xsd\{p}\" Visible="false" />"""));

        var dir = Directory.CreateDirectory(Path.Combine(repoRoot, "packages", packageId)).FullName;
        var csprojPath = Path.Combine(dir, packageId + ".csproj");
        var isNew = !File.Exists(csprojPath);
        File.WriteAllText(csprojPath, $"""
            <Project Sdk="Microsoft.NET.Sdk">

              <!-- Generated by scripts/add-schema-version.cs; re-run it instead of editing. -->
              <Import Project="..\..\build\VersionPackage.targets" />

              <PropertyGroup>
                <PackageId>{packageId}</PackageId>
                <Description>{description}</Description>
              </PropertyGroup>

              <ItemGroup>
            {references}
              </ItemGroup>

              <ItemGroup>
            {schemas}
              </ItemGroup>

            </Project>

            """);
        if (isNew)
            Run("dotnet", $"sln FpmlToolKit.slnx add --solution-folder packages \"{csprojPath}\"");
    }
    Console.WriteLine($"package projects: {views.Count()} versions");
}

void Add(string mainSchema)
{
    var version = Regex.Match(Path.GetFileName(mainSchema), @"^fpml-main-(\d+-\d+)\.xsd$") is { Success: true } m
        ? m.Groups[1].Value
        : throw new InvalidOperationException("main schema name is not fpml-main-<major>-<minor>.xsd");

    var targetNamespace = (string?)XDocument.Load(mainSchema).Root!.Attribute("targetNamespace")
        ?? throw new InvalidOperationException("main schema has no targetNamespace");
    var view = Regex.Match(targetNamespace, @"^http://www\.fpml\.org/FpML-5/([a-z]+)$") is { Success: true } v
        ? v.Groups[1].Value
        : throw new InvalidOperationException($"unexpected target namespace '{targetNamespace}' (only FpML 5.x views are supported)");

    var name = $"fpml-{version}-{view}";
    var schemas = CompileSchema(mainSchema, name);
    if (schemas is null)
        return;

    var projectDir = Path.Combine(repoRoot, name);
    if (Directory.Exists(projectDir))
        Console.WriteLine($"{name}: project already exists");
    else
        CreateProject(mainSchema, name, version, view, targetNamespace);

    ImportExamples(Path.GetDirectoryName(mainSchema)!, name, targetNamespace, schemas);
}

XmlSchemaSet? CompileSchema(string mainSchema, string name)
{
    var schemas = new XmlSchemaSet { XmlResolver = new XmlUrlResolver() };
    var errors = new List<string>();
    schemas.ValidationEventHandler += (_, e) =>
    {
        if (e.Severity == XmlSeverityType.Error)
            errors.Add($"{Path.GetFileName(e.Exception?.SourceUri)}:{e.Exception?.LineNumber}: {e.Message}");
    };
    using (var reader = XmlReader.Create(mainSchema))
        schemas.Add(null, reader);
    schemas.Compile();
    if (errors.Count == 0 && schemas.IsCompiled)
        return schemas;

    Console.Error.WriteLine($"{name}: schema does not compile, skipped");
    foreach (var error in errors.Take(5))
        Console.Error.WriteLine($"    {error}");
    failed++;
    return null;
}

void ImportExamples(string viewDir, string name, string targetNamespace, XmlSchemaSet schemas)
{
    var examplesDir = Path.Combine(repoRoot, "tests", "FpmlToolKit.Tests", "Examples", name);
    if (Directory.Exists(examplesDir))
    {
        Console.WriteLine($"{name}: examples already imported");
        return;
    }

    var candidates = new List<string>();
    foreach (var file in Directory.GetFiles(viewDir, "*.xml", SearchOption.AllDirectories).Order(StringComparer.Ordinal))
    {
        if (new FileInfo(file).Length > MaxExampleBytes)
            continue;
        XDocument doc;
        try { doc = XDocument.Load(file); }
        catch (XmlException) { continue; }
        if (doc.Root!.Name.NamespaceName != targetNamespace)
            continue;
        var valid = true;
        doc.Validate(schemas, (_, e) => valid &= e.Severity != XmlSeverityType.Error);
        if (valid)
            candidates.Add(file);
    }

    if (candidates.Count == 0)
    {
        Console.WriteLine($"{name}: no schema-valid examples found");
        return;
    }

    var picks = Enumerable.Range(0, Math.Min(ExamplesPerView, candidates.Count))
        .Select(i => candidates[i * candidates.Count / Math.Min(ExamplesPerView, candidates.Count)]);
    foreach (var file in picks)
    {
        var target = Path.Combine(examplesDir, Path.GetRelativePath(viewDir, file));
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
        File.Copy(file, target);
    }
    Console.WriteLine($"{name}: imported {Math.Min(ExamplesPerView, candidates.Count)} of {candidates.Count} schema-valid examples");
}

void CreateProject(string mainSchema, string name, string version, string view, string targetNamespace)
{
    var projectDir = Path.Combine(repoRoot, name);

    var xsdDir = Directory.CreateDirectory(Path.Combine(projectDir, "xsd")).FullName;
    var schemaFiles = Directory.GetFiles(Path.GetDirectoryName(mainSchema)!, "*.xsd");
    foreach (var file in schemaFiles)
        File.Copy(file, Path.Combine(xsdDir, Path.GetFileName(file)));

    var rootNamespace = name.Replace('-', '_');
    File.WriteAllText(Path.Combine(xsdDir, "namespaceconfig.xml"), $"""
        <?xml version="1.0" encoding="utf-8" ?>
        <Configuration xmlns="http://www.microsoft.com/xml/schema/linq">
          <Namespaces>
            <Namespace Schema="{targetNamespace}" Clr="{rootNamespace}"/>
            <Namespace Schema="http://www.w3.org/2000/09/xmldsig#" Clr="org.w3.xmldsig"/>
          </Namespaces>
        </Configuration>

        """);

    var dotted = version.Replace('-', '.');
    var csprojPath = Path.Combine(projectDir, name + ".csproj");
    File.WriteAllText(csprojPath, $"""
        <Project Sdk="Microsoft.NET.Sdk">

          <PropertyGroup>
            <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
            <RootNamespace>{rootNamespace}</RootNamespace>
            <AssemblyName>{name}</AssemblyName>
            <Description>Strongly typed LINQ to XSD classes for the FpML {dotted} {view} view.</Description>
          </PropertyGroup>

          <ItemGroup>
            <PackageReference Include="XObjectsCore" Version="3.4.23" />
          </ItemGroup>

          <ItemGroup>
            <LinqToXsdSchema Include="xsd\{Path.GetFileName(mainSchema)}" />
            <LinqToXsdConfiguration Include="xsd\namespaceconfig.xml" />
          </ItemGroup>

        </Project>

        """);

    Run("dotnet", $"sln FpmlToolKit.slnx add \"{csprojPath}\"");
    Console.WriteLine($"{name}: added ({schemaFiles.Length} schema files)");
}

void Run(string file, string arguments)
{
    using var process = Process.Start(new ProcessStartInfo(file, arguments)
    {
        WorkingDirectory = repoRoot,
        RedirectStandardOutput = true,
        RedirectStandardError = true,
    })!;
    process.WaitForExit();
    if (process.ExitCode != 0)
        throw new InvalidOperationException($"'{file} {arguments}' failed: {process.StandardError.ReadToEnd().Trim()}");
}

static string FindRepoRoot()
{
    for (var dir = new DirectoryInfo(Environment.CurrentDirectory); dir is not null; dir = dir.Parent)
    {
        if (File.Exists(Path.Combine(dir.FullName, "FpmlToolKit.slnx")))
            return dir.FullName;
    }
    throw new InvalidOperationException("run this from inside the FpmlToolKit.Net repository");
}
