// Creates fpml-<version>-<view> (5.x) and fpml-<version> (4.x) projects from FpML "Schema and Examples" downloads,
// adds them to FpmlToolKit.slnx, and copies a few of the official examples into the test project.
//
//   dotnet run scripts/add-schema-version.cs -- [--replace] <folder> [<folder> ...]
//   dotnet run scripts/add-schema-version.cs              (only regenerate the per-version package projects)
//
// Each folder is searched recursively for fpml-main-*.xsd; every match is one view (confirmation, reporting, ...).
// The version comes from the main schema's file name (fpml-main-5-13.xsd -> 5-13) and the view from its target
// namespace (http://www.fpml.org/FpML-5/confirmation -> confirmation; 4.x has no views).
//
// - The schema must compile (System.Xml.Schema) or the view is skipped; LinqToXsd fails silently on such schemas.
// - The XSDs next to the main schema are copied, byte for byte, into the new project's xsd/ folder.
// - ExamplesPerView schema-valid example documents, spread evenly across the view's examples, are copied to
//   tests/FpmlToolKit.Tests/Examples/<project>/, keeping their relative paths.
// - packages/FpmlToolKit.Fpml<version>/ is (re)generated for every FpML version in the repository: one NuGet package
//   per version, containing all of that version's view projects (see build/VersionPackage.targets).
// Existing projects and existing example folders are left untouched, so the script is safe to re-run. With --replace,
// an existing project's XSDs and examples are replaced by the ones in the given folders instead (moving a version to
// a newer FpML build); its namespaceconfig.xml and project file are kept.
//
// Afterwards, run scripts/official-files.cs to record where every copied file came from.

#nullable enable

using System.Diagnostics;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;

const int ExamplesPerView = 5;
const long MaxExampleBytes = 100_000;

var repoRoot = FindRepoRoot();
var sources = args.Where(a => !a.StartsWith("--")).ToList();
var replace = args.Contains("--replace");

foreach (var missing in sources.Where(s => !Directory.Exists(s)))
{
    Console.Error.WriteLine($"folder not found: {missing}");
    return 1;
}

var mainSchemas = sources
    .SelectMany(s => Directory.GetFiles(s, "fpml-main-*.xsd", SearchOption.AllDirectories))
    .Order()
    .ToList();
if (sources.Count > 0 && mainSchemas.Count == 0)
{
    Console.Error.WriteLine("no fpml-main-*.xsd found");
    return 1;
}

var failed = 0;
foreach (var mainSchema in mainSchemas)
{
    try
    {
        Add(mainSchema);
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"{mainSchema}: {ex.Message}");
        failed++;
    }
}
WriteVersionPackages();
return failed == 0 ? 0 : 1;

void WriteVersionPackages()
{
    var views = Directory.GetDirectories(repoRoot, "fpml-*")
        .Select(Path.GetFileName)
        .OfType<string>()
        .Where(n => File.Exists(Path.Combine(repoRoot, n, n + ".csproj")))
        .Select(n => (Name: n, Match: Regex.Match(n, @"^fpml-(\d+)-(\d+)(?:-([a-z]+))?$")))
        .Where(x => x.Match.Success)
        .GroupBy(x => (Major: int.Parse(x.Match.Groups[1].Value), Minor: int.Parse(x.Match.Groups[2].Value)))
        .OrderBy(g => g.Key);

    foreach (var version in views)
    {
        var (major, minor) = version.Key;
        var packageId = $"FpmlToolKit.Fpml{major}{minor}";
        var projects = version.Select(x => x.Name).Order(StringComparer.Ordinal).ToList();
        var viewNames = version.Select(x => x.Match.Groups[3].Value).Where(v => v.Length > 0).Order(StringComparer.Ordinal).ToList();
        var description = viewNames.Count == 0
            ? $"Strongly typed LINQ to XSD classes for FpML {major}.{minor}."
            : $"Strongly typed LINQ to XSD classes for FpML {major}.{minor}, one assembly per view: {string.Join(", ", viewNames)}.";

        var references = string.Join(Environment.NewLine, projects.Select(p => $"""    <ProjectReference Include="..\..\{p}\{p}.csproj" />"""));

        var dir = Directory.CreateDirectory(Path.Combine(repoRoot, "packages", packageId)).FullName;
        var csprojPath = Path.Combine(dir, packageId + ".csproj");
        var isNew = !File.Exists(csprojPath);
        File.WriteAllText(csprojPath, $"""
            <Project Sdk="Microsoft.NET.Sdk">

              <!-- Generated by scripts/add-schema-version.cs; re-run it instead of editing. -->
              <Import Project="..\..\build\VersionPackage.targets" />

              <PropertyGroup>
                <PackageId>{packageId}</PackageId>
                <Description>{description}</Description>
              </PropertyGroup>

              <ItemGroup>
            {references}
              </ItemGroup>

            </Project>

            """);
        if (isNew)
            Run("dotnet", $"sln FpmlToolKit.slnx add --solution-folder packages \"{csprojPath}\"");

        // Shown on the package's NuGet.org page (PackageReadmeFile in build/VersionPackage.targets).
        var rows = string.Join(Environment.NewLine, projects.Select(p =>
        {
            var view = Regex.Match(p, @"^fpml-\d+-\d+-([a-z]+)$") is { Success: true } m ? m.Groups[1].Value : "(all)";
            return $"| {view} | `{p}.dll` | `{p.Replace('-', '_')}` |";
        }));
        var exampleNamespace = projects[0].Replace('-', '_');
        // Contains braces, so it is kept out of the raw interpolated readme template below.
        const string printProblem = "Console.WriteLine($\"{problem.Severity}: {problem.Message}\");";
        var exampleDocument = viewNames.Count == 0
            ? $"an FpML {major}.{minor} document"
            : $"an FpML {major}.{minor} {viewNames[0]} view document (use the matching namespace for other views)";
        File.WriteAllText(Path.Combine(dir, "README.md"), $"""
            # {packageId}

            {description}

            Generated from the FpML {major}.{minor} schemas with [LinqToXsdCore](https://github.com/mamift/LinqToXsdCore),
            as part of [FpmlToolKit.Net](https://github.com/ehosca/FpmlToolKit.Net). Targets .NET Standard 2.0 and .NET 10.

            | View | Assembly | Namespace |
            |---|---|---|
            {rows}

            Each assembly has its own copy of the W3C XML Signature types, in `<namespace>.xmldsig`.

            ## Usage

            ```csharp
            using {exampleNamespace};

            // Load {exampleDocument}; Root is the typed root element.
            var doc = XRoot.Load("document.xml");
            Console.WriteLine(doc.Root.GetType().Name);

            // Validate against the schemas embedded in the assembly (no files or network access needed).
            foreach (var problem in FpmlSchema.Validate(doc.Root))
                {printProblem}
            ```

            Root element types also have static `Load` and `Parse` methods, and every type can be built in code and
            serialised with `ToString()`. Each assembly embeds the schemas it was generated from: `FpmlSchema` validates
            documents and typed elements (`Validate`, `IsValid`), returns a compiled `XmlSchemaSet` (`CreateSchemaSet`) and
            opens the raw files (`SchemaFileNames`, `OpenSchema`).

            ## License

            FpmlToolKit.Net is MIT licensed. The FpML schemas are licensed by ISDA under the
            [FpML Public License](https://www.fpml.org/the_standard/fpml-public-license/); see `LICENSE.txt` and
            `THIRD-PARTY-NOTICES.md` in the package.

            """);
    }
    Console.WriteLine($"package projects: {views.Count()} versions");
}

void Add(string mainSchema)
{
    var version = Regex.Match(Path.GetFileName(mainSchema), @"^fpml-main-(\d+-\d+)\.xsd$") is { Success: true } m
        ? m.Groups[1].Value
        : throw new InvalidOperationException("main schema name is not fpml-main-<major>-<minor>.xsd");

    var targetNamespace = (string?)XDocument.Load(mainSchema).Root!.Attribute("targetNamespace")
        ?? throw new InvalidOperationException("main schema has no targetNamespace");
    string? view = Regex.Match(targetNamespace, @"^http://www\.fpml\.org/FpML-5/([a-z]+)$") is { Success: true } v
        ? v.Groups[1].Value
        : Regex.IsMatch(targetNamespace, $@"^http://www\.fpml\.org/\d{{4}}/FpML-{version}$")
            ? null
            : throw new InvalidOperationException($"unexpected target namespace '{targetNamespace}' for FpML {version}");

    var name = view is null ? $"fpml-{version}" : $"fpml-{version}-{view}";
    var schemas = CompileSchema(mainSchema, name);
    if (schemas is null)
        return;

    var projectDir = Path.Combine(repoRoot, name);
    if (!Directory.Exists(projectDir))
        CreateProject(mainSchema, name, version, view, targetNamespace);
    else if (replace)
        ReplaceSchemas(mainSchema, name);
    else
        Console.WriteLine($"{name}: project already exists");

    ImportExamples(Path.GetDirectoryName(mainSchema)!, name, targetNamespace, schemas);
}

XmlSchemaSet? CompileSchema(string mainSchema, string name)
{
    var schemas = new XmlSchemaSet { XmlResolver = new XmlUrlResolver() };
    var errors = new List<string>();
    schemas.ValidationEventHandler += (_, e) =>
    {
        if (e.Severity == XmlSeverityType.Error)
            errors.Add($"{Path.GetFileName(e.Exception?.SourceUri)}:{e.Exception?.LineNumber}: {e.Message}");
    };
    using (var reader = XmlReader.Create(mainSchema))
        schemas.Add(null, reader);
    schemas.Compile();
    if (errors.Count == 0 && schemas.IsCompiled)
        return schemas;

    Console.Error.WriteLine($"{name}: schema does not compile, skipped");
    foreach (var error in errors.Take(5))
        Console.Error.WriteLine($"    {error}");
    failed++;
    return null;
}

void ImportExamples(string viewDir, string name, string targetNamespace, XmlSchemaSet schemas)
{
    var examplesDir = Path.Combine(repoRoot, "tests", "FpmlToolKit.Tests", "Examples", name);
    if (Directory.Exists(examplesDir) && replace)
        Directory.Delete(examplesDir, recursive: true);
    if (Directory.Exists(examplesDir))
    {
        Console.WriteLine($"{name}: examples already imported");
        return;
    }

    var candidates = new List<string>();
    foreach (var file in Directory.GetFiles(viewDir, "*.xml", SearchOption.AllDirectories).Order(StringComparer.Ordinal))
    {
        if (new FileInfo(file).Length > MaxExampleBytes)
            continue;
        XDocument doc;
        try { doc = XDocument.Load(file); }
        catch (XmlException) { continue; }
        if (doc.Root!.Name.NamespaceName != targetNamespace)
            continue;
        var valid = true;
        doc.Validate(schemas, (_, e) => valid &= e.Severity != XmlSeverityType.Error);
        if (valid)
            candidates.Add(file);
    }

    if (candidates.Count == 0)
    {
        Console.WriteLine($"{name}: no schema-valid examples found");
        return;
    }

    var picks = Enumerable.Range(0, Math.Min(ExamplesPerView, candidates.Count))
        .Select(i => candidates[i * candidates.Count / Math.Min(ExamplesPerView, candidates.Count)]);
    foreach (var file in picks)
    {
        var target = Path.Combine(examplesDir, Path.GetRelativePath(viewDir, file));
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
        File.Copy(file, target);
    }
    Console.WriteLine($"{name}: imported {Math.Min(ExamplesPerView, candidates.Count)} of {candidates.Count} schema-valid examples");
}

int CopySchemas(string mainSchema, string xsdDir)
{
    var schemaFiles = Directory.GetFiles(Path.GetDirectoryName(mainSchema)!, "*.xsd");
    foreach (var file in schemaFiles)
        File.Copy(file, Path.Combine(xsdDir, Path.GetFileName(file)));
    return schemaFiles.Length;
}

void ReplaceSchemas(string mainSchema, string name)
{
    var projectDir = Path.Combine(repoRoot, name);
    var csproj = File.ReadAllText(Path.Combine(projectDir, name + ".csproj"));
    if (!csproj.Contains($@"<LinqToXsdSchema Include=""xsd\{Path.GetFileName(mainSchema)}"" />"))
        throw new InvalidOperationException($"{name}.csproj does not generate from xsd\\{Path.GetFileName(mainSchema)}");

    var xsdDir = Path.Combine(projectDir, "xsd");
    foreach (var file in Directory.GetFiles(xsdDir, "*.xsd"))
        File.Delete(file);
    Console.WriteLine($"{name}: replaced schemas ({CopySchemas(mainSchema, xsdDir)} files)");
}

void CreateProject(string mainSchema, string name, string version, string? view, string targetNamespace)
{
    var projectDir = Path.Combine(repoRoot, name);

    var xsdDir = Directory.CreateDirectory(Path.Combine(projectDir, "xsd")).FullName;
    var schemaFileCount = CopySchemas(mainSchema, xsdDir);

    var rootNamespace = name.Replace('-', '_');
    File.WriteAllText(Path.Combine(xsdDir, "namespaceconfig.xml"), $"""
        <?xml version="1.0" encoding="utf-8" ?>
        <Configuration xmlns="http://www.microsoft.com/xml/schema/linq">
          <Namespaces>
            <Namespace Schema="{targetNamespace}" Clr="{rootNamespace}"/>
            <Namespace Schema="http://www.w3.org/2000/09/xmldsig#" Clr="{rootNamespace}.xmldsig"/>
          </Namespaces>
        </Configuration>

        """);

    var dotted = version.Replace('-', '.');
    var csprojPath = Path.Combine(projectDir, name + ".csproj");
    File.WriteAllText(csprojPath, $"""
        <Project Sdk="Microsoft.NET.Sdk">

          <PropertyGroup>
            <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
            <RootNamespace>{rootNamespace}</RootNamespace>
            <AssemblyName>{name}</AssemblyName>
            <Description>Strongly typed LINQ to XSD classes for {(view is null ? $"FpML {dotted}" : $"the FpML {dotted} {view} view")}.</Description>
          </PropertyGroup>

          <ItemGroup>
            <PackageReference Include="XObjectsCore" Version="$(XObjectsCoreVersion)" />
          </ItemGroup>

          <ItemGroup>
            <LinqToXsdSchema Include="xsd\{Path.GetFileName(mainSchema)}" />
            <LinqToXsdConfiguration Include="xsd\namespaceconfig.xml" />
          </ItemGroup>

        </Project>

        """);

    Run("dotnet", $"sln FpmlToolKit.slnx add \"{csprojPath}\"");
    Console.WriteLine($"{name}: added ({schemaFileCount} schema files)");
}

void Run(string file, string arguments)
{
    using var process = Process.Start(new ProcessStartInfo(file, arguments)
    {
        WorkingDirectory = repoRoot,
        RedirectStandardOutput = true,
        RedirectStandardError = true,
    })!;
    process.WaitForExit();
    if (process.ExitCode != 0)
        throw new InvalidOperationException($"'{file} {arguments}' failed: {process.StandardError.ReadToEnd().Trim()}");
}

static string FindRepoRoot()
{
    for (var dir = new DirectoryInfo(Environment.CurrentDirectory); dir is not null; dir = dir.Parent)
    {
        if (File.Exists(Path.Combine(dir.FullName, "FpmlToolKit.slnx")))
            return dir.FullName;
    }
    throw new InvalidOperationException("run this from inside the FpmlToolKit.Net repository");
}
